from django.db import models


class ManualControl(models.Model):
    controller = models.OneToOneField("Controller", on_delete=models.CASCADE, related_name="manual_control")
    target_temperature = models.FloatField(default=50)
    active = models.BooleanField(default=False)
    direct_mode = models.BooleanField(default=False)
    pump_on = models.BooleanField(default=False)
    reported_pump_on = models.BooleanField(null=True, blank=True)
    pump_voltage = models.FloatField(null=True, blank=True)
    pump_current = models.FloatField(null=True, blank=True)
    warning_delta = models.FloatField(default=10)
    warning_mode = models.CharField(max_length=10, default="degrees")
    revision = models.PositiveIntegerField(default=0)
    reported_revision = models.PositiveIntegerField(null=True, blank=True)
    reported_power = models.FloatField(default=0)
    reported_at = models.DateTimeField(null=True, blank=True)
    reported_output_mode = models.CharField(max_length=16, blank=True)
    measured_voltage = models.FloatField(null=True, blank=True)
    estimate_started_at = models.DateTimeField(null=True, blank=True)
    pid_kp = models.FloatField(default=10)
    pid_ki = models.FloatField(default=0.1)
    pid_kd = models.FloatField(default=5)
    window_ms = models.PositiveIntegerField(default=2000)
    reported_ssr_on = models.BooleanField(null=True, blank=True)
    reported_window_ms = models.PositiveIntegerField(null=True, blank=True)
    reported_on_time_ms = models.PositiveIntegerField(null=True, blank=True)
    reported_enabled = models.BooleanField(null=True, blank=True)
    reported_fault = models.BooleanField(default=False)


class ManualControlSample(models.Model):
    control = models.ForeignKey(ManualControl, on_delete=models.CASCADE, related_name="samples")
    temperature = models.FloatField(null=True)
    target_temperature = models.FloatField()
    power_percent = models.FloatField(null=True, blank=True)
    signal_voltage = models.FloatField(null=True, blank=True)
    ssr_on = models.BooleanField(null=True, blank=True)
    output_mode = models.CharField(max_length=16, blank=True)
    measured_voltage = models.FloatField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
