# Generated by Django 6.0.5 on 2026-05-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brewery",
            name="last_seen_at",
        ),
    ]
