# Generated by Django 6.0.5 on 2026-06-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_brewery_last_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="controller",
            name="ip",
            field=models.CharField(default="0.0.0.0", max_length=255),
        ),
    ]
