# Generated by Django 4.2.30 on 2026-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brewsession_paused_at_brewsession_paused_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewsession',
            name='mode',
            field=models.CharField(choices=[('demo', '3-minute demo'), ('standard', 'Standard recipe timing')], default='demo', max_length=16),
        ),
        migrations.AddField(
            model_name='brewsession',
            name='step_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
