# Generated by Django 4.2.30 on 2026-09-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_brewsession_mode_brewsession_step_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewsession',
            name='step_elapsed_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brewsession',
            name='temperature_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brewsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_temperature', 'Waiting for temperature'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
    ]
