# Generated by Django 4.2.30 on 2026-09-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_brewsession_step_elapsed_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='mode',
            field=models.CharField(choices=[('reach_temperature', 'Reach temperature'), ('hold_temperature', 'Temperature hold')], default='hold_temperature', max_length=32),
        ),
        migrations.AlterField(
            model_name='brewsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('heating', 'Reaching temperature'), ('waiting_temperature', 'Waiting for temperature'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
    ]
