# Generated by Django 6.0.5 on 2026-10-01 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_controller_wifi_reset_command"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_temperature", models.FloatField(default=50)),
                ("active", models.BooleanField(default=False)),
                ("warning_delta", models.FloatField(default=10)),
                ("warning_mode", models.CharField(default="degrees", max_length=10)),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "reported_revision",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("reported_power", models.FloatField(default=0)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "controller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_control",
                        to="main.controller",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualControlSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(null=True)),
                ("target_temperature", models.FloatField()),
                ("power_percent", models.FloatField()),
                ("signal_voltage", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="main.manualcontrol",
                    ),
                ),
            ],
        ),
    ]
