# Generated by Django 6.0.5 on 2026-10-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_manualcontrol_manualcontrolsample"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualcontrol",
            name="measured_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="reported_output_mode",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="manualcontrolsample",
            name="measured_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
