# Generated by Django 6.0.5 on 2026-10-01 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_manualcontrol_measured_voltage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brewery",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="estimate_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "volume_liters",
                    models.DecimalField(
                        decimal_places=1,
                        default=20,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    "controller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vessel",
                        to="main.controller",
                    ),
                ),
            ],
        ),
    ]
