# Generated by Django 6.0.5 on 2026-10-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_existing_controller_vessels"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualcontrol",
            name="pid_kd",
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="pid_ki",
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="pid_kp",
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="reported_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="reported_fault",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="reported_on_time_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="reported_ssr_on",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="reported_window_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="window_ms",
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name="manualcontrolsample",
            name="output_mode",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="manualcontrolsample",
            name="ssr_on",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="manualcontrolsample",
            name="power_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="manualcontrolsample",
            name="signal_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
