# Generated by Django 6.0.5 on 2026-10-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_pause_legacy_manual_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualcontrol",
            name="direct_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="pump_on",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="reported_pump_on",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
