# Generated by Django 6.0.5 on 2026-10-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_manualcontrol_direct_mode_manualcontrol_pump_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualcontrol",
            name="pump_current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manualcontrol",
            name="pump_voltage",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
