# Generated by Django 6.0.5 on 2026-10-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_manualcontrol_pump_current_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brewsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("heating", "Reaching temperature"),
                    ("waiting_temperature", "Waiting for temperature"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
